// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.0
// source: const.proto

package pb_lib

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Services int32

const (
	Services_unknown_service Services = 0
	// Services
	Services_orchestrator Services = 1
	Services_backend      Services = 2
	Services_storage      Services = 3
)

// Enum value maps for Services.
var (
	Services_name = map[int32]string{
		0: "unknown_service",
		1: "orchestrator",
		2: "backend",
		3: "storage",
	}
	Services_value = map[string]int32{
		"unknown_service": 0,
		"orchestrator":    1,
		"backend":         2,
		"storage":         3,
	}
)

func (x Services) Enum() *Services {
	p := new(Services)
	*p = x
	return p
}

func (x Services) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Services) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[0].Descriptor()
}

func (Services) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[0]
}

func (x Services) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Services.Descriptor instead.
func (Services) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{0}
}

type Permission int32

const (
	Permission_unknown_permission Permission = 0
	// Role
	Permission_role_create Permission = 1
	Permission_role_read   Permission = 2
	Permission_role_update Permission = 3
	Permission_role_delete Permission = 4
	Permission_role_list   Permission = 5
	// User
	Permission_user_create         Permission = 6
	Permission_user_read           Permission = 7
	Permission_user_update         Permission = 8
	Permission_user_delete         Permission = 9
	Permission_user_list           Permission = 10
	Permission_user_blocked        Permission = 11
	Permission_user_unblocked      Permission = 12
	Permission_user_password_reset Permission = 13
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0:  "unknown_permission",
		1:  "role_create",
		2:  "role_read",
		3:  "role_update",
		4:  "role_delete",
		5:  "role_list",
		6:  "user_create",
		7:  "user_read",
		8:  "user_update",
		9:  "user_delete",
		10: "user_list",
		11: "user_blocked",
		12: "user_unblocked",
		13: "user_password_reset",
	}
	Permission_value = map[string]int32{
		"unknown_permission":  0,
		"role_create":         1,
		"role_read":           2,
		"role_update":         3,
		"role_delete":         4,
		"role_list":           5,
		"user_create":         6,
		"user_read":           7,
		"user_update":         8,
		"user_delete":         9,
		"user_list":           10,
		"user_blocked":        11,
		"user_unblocked":      12,
		"user_password_reset": 13,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[1].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[1]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{1}
}

type Unit int32

const (
	Unit_unknown_unit Unit = 0
	Unit_pc           Unit = 1 // штук
	Unit_g            Unit = 2 // грамм
	Unit_ml           Unit = 3 // миллилитров
)

// Enum value maps for Unit.
var (
	Unit_name = map[int32]string{
		0: "unknown_unit",
		1: "pc",
		2: "g",
		3: "ml",
	}
	Unit_value = map[string]int32{
		"unknown_unit": 0,
		"pc":           1,
		"g":            2,
		"ml":           3,
	}
)

func (x Unit) Enum() *Unit {
	p := new(Unit)
	*p = x
	return p
}

func (x Unit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Unit) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[2].Descriptor()
}

func (Unit) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[2]
}

func (x Unit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Unit.Descriptor instead.
func (Unit) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{2}
}

var File_const_proto protoreflect.FileDescriptor

var file_const_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73,
	0x75, 0x64, 0x6f, 0x6b, 0x75, 0x2a, 0x4b, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x12, 0x13, 0x0a, 0x0f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x10, 0x03, 0x2a, 0x85, 0x02, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x12, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x72, 0x6f, 0x6c,
	0x65, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x72, 0x6f,
	0x6c, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x72, 0x6f, 0x6c,
	0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x72, 0x6f,
	0x6c, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x72,
	0x6f, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x08, 0x12, 0x0f, 0x0a, 0x0b, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x09, 0x12, 0x0d, 0x0a, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x10, 0x0a, 0x12, 0x10, 0x0a, 0x0c, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x10, 0x0b, 0x12, 0x12, 0x0a,
	0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x6e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x10,
	0x0c, 0x12, 0x17, 0x0a, 0x13, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x74, 0x10, 0x0d, 0x2a, 0x2f, 0x0a, 0x04, 0x55, 0x6e,
	0x69, 0x74, 0x12, 0x10, 0x0a, 0x0c, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x75, 0x6e,
	0x69, 0x74, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x70, 0x63, 0x10, 0x01, 0x12, 0x05, 0x0a, 0x01,
	0x67, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x6d, 0x6c, 0x10, 0x03, 0x42, 0x23, 0x5a, 0x21, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f,
	0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x62, 0x5f, 0x6c, 0x69, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_const_proto_rawDescOnce sync.Once
	file_const_proto_rawDescData = file_const_proto_rawDesc
)

func file_const_proto_rawDescGZIP() []byte {
	file_const_proto_rawDescOnce.Do(func() {
		file_const_proto_rawDescData = protoimpl.X.CompressGZIP(file_const_proto_rawDescData)
	})
	return file_const_proto_rawDescData
}

var file_const_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_const_proto_goTypes = []interface{}{
	(Services)(0),   // 0: sudoku.Services
	(Permission)(0), // 1: sudoku.Permission
	(Unit)(0),       // 2: sudoku.Unit
}
var file_const_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_const_proto_init() }
func file_const_proto_init() {
	if File_const_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_const_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_const_proto_goTypes,
		DependencyIndexes: file_const_proto_depIdxs,
		EnumInfos:         file_const_proto_enumTypes,
	}.Build()
	File_const_proto = out.File
	file_const_proto_rawDesc = nil
	file_const_proto_goTypes = nil
	file_const_proto_depIdxs = nil
}
